// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

package com.stub.person.v1;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stub.person.v1.PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
